import 'package:flutter/material.dart';
import 'package:tetris/theme/app_theme.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: kBackgroundColor,
      appBar: AppBar(
        title: const Text('Privacy Policy'),
        backgroundColor: kSurfaceColor,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new_rounded),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: const SingleChildScrollView(
        padding: EdgeInsets.symmetric(horizontal: 20, vertical: 24),
        child: _PolicyContent(),
      ),
    );
  }
}

class _PolicyContent extends StatelessWidget {
  const _PolicyContent();

  @override
  Widget build(BuildContext context) {
    return const Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        _PolicyHeader(
          icon: Icons.privacy_tip_outlined,
          title: 'Privacy Policy',
          lastUpdated: 'Last updated: January 1, 2026',
        ),
        SizedBox(height: 24),
        _PolicySection(
          title: '1. Introduction',
          content:
              'Welcome to Tetris. We are committed to protecting your personal information and your right to privacy. This Privacy Policy explains how we collect, use, and safeguard your information when you use our mobile application.',
        ),
        _PolicySection(
          title: '2. Information We Collect',
          content:
              'We do not collect any personally identifiable information. Our app operates entirely on your device and does not require account registration, login, or personal data submission.\n\nWe may collect anonymous usage statistics such as game scores and session duration solely for improving the user experience. This data is not linked to any personal identity.',
        ),
        _PolicySection(
          title: '3. How We Use Your Information',
          content:
              'Any anonymous data collected is used exclusively to:\n\n• Improve game performance and stability\n• Understand how users interact with the app\n• Fix bugs and enhance features\n\nWe do not sell, trade, or share any data with third parties.',
        ),
        _PolicySection(
          title: '4. Data Storage',
          content:
              'Game progress, scores, and settings are stored locally on your device. This data never leaves your device and is not transmitted to any server. Uninstalling the app will remove all locally stored data.',
        ),
        _PolicySection(
          title: '5. Third-Party Services',
          content:
              'This application does not integrate any third-party analytics, advertising networks, or tracking services. No third party has access to any data generated by your use of this app.',
        ),
        _PolicySection(
          title: '6. Children\'s Privacy',
          content:
              'Our app is suitable for users of all ages. We do not knowingly collect any personal information from children under the age of 13. Since we collect no personal data at all, the app is safe for children to use.',
        ),
        _PolicySection(
          title: '7. Security',
          content:
              'We take data security seriously. Since all data remains on your device and no personal information is collected, the risk of a data breach affecting your privacy is minimal. We recommend keeping your device and operating system up to date.',
        ),
        _PolicySection(
          title: '8. Changes to This Policy',
          content:
              'We may update this Privacy Policy from time to time. Any changes will be reflected in the "Last updated" date at the top of this page. Continued use of the app after changes constitutes your acceptance of the updated policy.',
        ),
        _PolicySection(
          title: '9. Contact Us',
          content:
              'If you have any questions or concerns about this Privacy Policy, please contact us. We are committed to resolving any privacy-related issues promptly and transparently.',
        ),
        SizedBox(height: 32),
        _PolicyFooter(),
      ],
    );
  }
}

class _PolicyHeader extends StatelessWidget {
  final IconData icon;
  final String title;
  final String lastUpdated;

  const _PolicyHeader({
    required this.icon,
    required this.title,
    required this.lastUpdated,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        gradient: const LinearGradient(
          colors: [kPrimaryColor, kPrimaryDark],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
        borderRadius: BorderRadius.circular(16),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: Colors.white.withValues(alpha: 0.2),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Icon(icon, color: Colors.white, size: 28),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  title,
                  style: const TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  lastUpdated,
                  style: TextStyle(
                    color: Colors.white.withValues(alpha: 0.75),
                    fontSize: 12,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _PolicySection extends StatelessWidget {
  final String title;
  final String content;

  const _PolicySection({required this.title, required this.content});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: const TextStyle(
              color: kPrimaryLight,
              fontSize: 16,
              fontWeight: FontWeight.w700,
              letterSpacing: 0.3,
            ),
          ),
          const SizedBox(height: 8),
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: kSurfaceColor,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: const Color(0xFF2A2A4A)),
            ),
            child: Text(
              content,
              style: const TextStyle(
                color: kTextSecondary,
                fontSize: 14,
                height: 1.65,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _PolicyFooter extends StatelessWidget {
  const _PolicyFooter();

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: kAccentColor.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: kAccentColor.withValues(alpha: 0.3)),
      ),
      child: const Row(
        children: [
          Icon(Icons.verified_outlined, color: kAccentColor, size: 20),
          SizedBox(width: 12),
          Expanded(
            child: Text(
              'Your privacy is important to us. We are fully committed to protecting your data.',
              style: TextStyle(
                color: kAccentColor,
                fontSize: 13,
                fontStyle: FontStyle.italic,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
